#!/bin/bash
# Script para subir el proyecto a GitHub

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      SUBIR PROYECTO A GITHUB                              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Verificar que git está instalado
if ! command -v git &> /dev/null; then
    echo "❌ Git no está instalado. Instálalo primero:"
    echo "   brew install git"
    exit 1
fi

echo "📝 PASOS PARA SUBIR A GITHUB:"
echo ""
echo "1️⃣  CREA UN REPOSITORIO EN GITHUB"
echo "   • Ve a https://github.com/new"
echo "   • Nombre: 'guided-interface-marinos' (o el que prefieras)"
echo "   • Descripción: 'Guía interactiva: Técnicas en gestión marino-costera'"
echo "   • NO inicialices con README"
echo "   • Copia la URL del repositorio (HTTPS o SSH)"
echo ""
echo "2️⃣  EJECUTA ESTOS COMANDOS EN TERMINAL:"
echo ""
echo "   cd \"$(pwd)\""
echo ""
echo "   # Inicializar git (si no está ya inicializado)"
echo "   git init"
echo ""
echo "   # Agregar archivos"
echo "   git add ."
echo ""
echo "   # Commit inicial"
echo "   git commit -m 'Initial commit: Interfaz interactiva de casos educativos'"
echo ""
echo "   # Agregar remote (reemplaza con tu URL)"
echo "   git remote add origin https://github.com/TU_USUARIO/TU_REPO.git"
echo ""
echo "   # Cambiar rama a main (GitHub Pages)"
echo "   git branch -M main"
echo ""
echo "   # Subir"
echo "   git push -u origin main"
echo ""
echo "3️⃣  HABILITA GITHUB PAGES"
echo "   • Ve a Settings del repositorio"
echo "   • GitHub Pages → Branch: main → Save"
echo "   • Tu interfaz estará en:"
echo "     https://TU_USUARIO.github.io/TU_REPO/index.html"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 PASOS AUTOMÁTICOS (opcional):"
echo ""
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: Guía interactiva marino-costera'"
echo "   git remote add origin [tu-url-github]"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
